= Quarkus Batik

include::./includes/attributes.adoc[]

A Quarkus extension that lets you use https://xmlgraphics.apache.org/batik/[Apache Batik], a Java-based toolkit for applications or applets that want to use images in the Scalable Vector Graphics (SVG) format for various purposes, such as display, generation or manipulation.

The project’s ambition is to give developers a set of core modules that can be used together or individually to support specific SVG solutions. Examples of modules are the SVG Parser, the SVG Generator and the SVG DOM. Another ambition for the Batik project is to make it highly extensible —for example, Batik allows the developer to handle custom SVG elements. Even though the goal of the project is to provide a set of core modules, one of the deliverables is a full-fledged SVG browser implementation that validates the various modules and their inter-operability.

IMPORTANT: The main purpose of this extension is to make Batik work in a native executable built with GraalVM/Mandrel.

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.batik:quarkus-batik` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.batik</groupId>
    <artifactId>quarkus-batik</artifactId>
    <version>{project-version}</version>
</dependency>
----